spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://ep-spring-band-aqjp94bs-pooler.c-8.us-east-1.aws.neon.tech/libraryhub_db?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_bF4okpPUge1j
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com # Servidor SMTP de gmail
    port: 587
    username: jgcode.apps@gmail.com
    password: tazjqlznuikpjufq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 9fE2L1pQ7rXs82vHkP1bWz6Yt8dA3rMfQ9uL7pHcV4sN0mQ2xA8dC5rT9hK1vB3X
  expiration: 86400000


